#!/usr/bin/env bash

set -Eeuo pipefail

readonly INCOMING_DIR='/var/lib/aibar-deploy/incoming'
readonly DEPLOY_SCRIPT='/usr/local/sbin/aibar-deploy-release'
readonly ORIGINAL_COMMAND="${SSH_ORIGINAL_COMMAND:-}"

case "$ORIGINAL_COMMAND" in
  sftp|internal-sftp|/usr/lib/openssh/sftp-server|'/usr/lib/openssh/sftp-server ')
    exec /usr/lib/openssh/sftp-server -d "$INCOMING_DIR" -u 027
    ;;
esac

if [[ "$ORIGINAL_COMMAND" =~ ^deploy\ ([0-9]{8}T[0-9]{6}Z-[0-9a-f]{7,40})\ ([0-9a-f]{64})$ ]]; then
  exec sudo -n "$DEPLOY_SCRIPT" "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}"
fi

printf 'Unsupported deployment command.\n' >&2
exit 126
